CREATE DATABASE RESTAURANT;
USE RESTAURANT;
drop database restaurant;
CREATE TABLE USERS(
		USERNAME VARCHAR(100) PRIMARY KEY,
		FULLNAME VARCHAR(100),
		PASS TEXT,
        EMAIL VARCHAR(100),
		SDT INT
);
SELECT * FROM USERS;
CREATE TABLE EMPLOYEES(
		USERNAME VARCHAR(100) PRIMARY KEY,
		FULLNAME VARCHAR(100),
		PASS TEXT,
		BIRTHDAY DATE,
		SDT INT,
		EMAIL VARCHAR(100),
		ADDRESS VARCHAR(100)
);
SELECT * FROM EMPLOYEES;
select * from USERS;

CREATE TABLE MANAGER(
		USERNAME VARCHAR(100) PRIMARY KEY,
		FULLNAME VARCHAR(100),
		PASS TEXT,
		SDT INT,
		EMAIL VARCHAR(100)
);
INSERT INTO MANAGER VALUE('thuyngan','Thúy Ngân','thuyngan',0123456789,'ngan@gmail.com');
select * from manager;


CREATE TABLE DISH (
    IDDISH INT PRIMARY KEY AUTO_INCREMENT,
    DISHNAME VARCHAR(100),
    PRICE INT,
    DESCRIP VARCHAR(200),
	TYPEDISH VARCHAR(50),
    PICTURE VARCHAR(200)
);
ALTER TABLE DISH AUTO_INCREMENT = 1;



CREATE TABLE CART(
	IDCART VARCHAR(30),
    QUANTITY INT NOT NULL,
	PRICE INT NOT NULL,
    TOTALPRICE INT NOT NULL,
    NAMECUST VARCHAR(100) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    IDDISH INT NOT NULL,
    PRIMARY KEY(IDCART,IDDISH)
);
ALTER TABLE CART ADD CONSTRAINT FK_DCART FOREIGN KEY(IDDISH) REFERENCES DISH(IDDISH);

CREATE TABLE PAYMENT(
	IDPAY INT AUTO_INCREMENT,
    QUANTITY INT NOT NULL,
    PRICE INT NOT NULL,
    TOTALPRICE INT NOT NULL,
    PAYTIME DATETIME NOT NULL,
    METHODS VARCHAR(100),
    IDCART VARCHAR(30) NOT NULL,
    PRIMARY KEY(IDPAY,IDCART)
);
ALTER TABLE PAYMENT ADD CONSTRAINT FK_DPAY FOREIGN KEY(IDCART) REFERENCES CART(IDCART);

#------------------- DROP-------------------------------
#ALTER TABLE PAYMENT DROP FOREIGN KEY FK_UPAY;
#ALTER TABLE PAYMENT DROP FOREIGN KEY FK_DPAY;
#ALTER TABLE CART DROP FOREIGN KEY FK_UCART;
#ALTER TABLE CART DROP FOREIGN KEY FK_DCART;
#DROP TABLE USERS;
#DROP TABLE CHECKCODE;
#DROP TABLE DISH;
#DROP TABLE CART;
#DROP TABLE PAYMENT;

#------------------- INSERT-------------------------------

SELECT * FROM USERS;
SELECT * FROM EMPLOYEES;

# add admin # default
#DELETE FROM EMPLOYEES WHERE USERNAME like 'nam12345';


# add dish
SELECT * FROM DISH;
INSERT INTO DISH(DISHNAME,PRICE,DESCRIP,TYPEDISH,PICTURE) VALUE('Bò Bít Tết',50000,'Đây là món Bò Bít Tết','food','bobittet.png');
INSERT INTO DISH(DISHNAME,PRICE,DESCRIP,TYPEDISH,PICTURE) VALUE('Bò Kho',25000,'Đây là món Bò Kho','food','bokho.png');
INSERT INTO DISH(DISHNAME,PRICE,DESCRIP,TYPEDISH,PICTURE) VALUE('Mỳ spaghetti',45000,'Đây là món Mỳ spaghetti','food','myspa.png');
INSERT INTO DISH(DISHNAME,PRICE,DESCRIP,TYPEDISH,PICTURE) VALUE('Mỳ Hải Sản',35000,'Đây là món Mỳ Hải Sản','food','myhaisan.png');
INSERT INTO DISH(DISHNAME,PRICE,DESCRIP,TYPEDISH,PICTURE) VALUE('Cơm Xèo Hải sản',30000,'Đây là món Cơm Xèo Hải sản','food','comhaisan.png');
INSERT INTO DISH(DISHNAME,PRICE,DESCRIP,TYPEDISH,PICTURE) VALUE('Cơm Xèo Thịt Bằm',30000,'Đây là món Cơm Xèo Thịt Bằm','food','comthit.png');

INSERT INTO DISH(DISHNAME,PRICE,DESCRIP,TYPEDISH,PICTURE) VALUE('Pepsi',10000,'Đây là nước Pepsi','drink','pepsi.png');
INSERT INTO DISH(DISHNAME,PRICE,DESCRIP,TYPEDISH,PICTURE) VALUE('7 Up',10000,'Đây là nước 7 Up','drink','sevenup.png');
INSERT INTO DISH(DISHNAME,PRICE,DESCRIP,TYPEDISH,PICTURE) VALUE('Trà Sữa',15000,'Đây là Trà Sữa','drink','trasua.png');
INSERT INTO DISH(DISHNAME,PRICE,DESCRIP,TYPEDISH,PICTURE) VALUE('Bia Tiger',15000,'Đây là Bia Tiger','drink','tiger.png');

#DELETE FROM DISH WHERE IDCART >= 1000000;

#update DISH set PICTURE = 'my_spa.jpg' where IDDISH = 1000002;

# add cart  # customer add on cart
#SELECT * FROM CART;
#SELECT * FROM CART where IDCART not in (select IDCART from PAYMENT);

#DELETE FROM CART WHERE IDPAY >= 0;
#INSERT INTO CART VALUE('0101',2,50000,PRICE*QUANTITY,'hoainam','082847545',1);
#INSERT INTO CART VALUE('0101',4,25000,PRICE*QUANTITY,'hoainam','082847545',2);
#INSERT INTO CART VALUE('0102',6,25000,PRICE*QUANTITY,'hoainam','082847545',2);
#INSERT INTO CART VALUE('0102',1,30000,PRICE*QUANTITY,'hoainam','082847545',5);
#INSERT INTO CART VALUE('0103',2,30000,PRICE*QUANTITY,'hoainam','082847545',5);

#UPDATE CART SET QUANTITY = 33,TOTALPRICE = QUANTITY*PRICE WHERE IDCART = 10000000;


# add payment     # admin use to analysis revenue
SELECT * FROM PAYMENT;	
DELETE FROM PAYMENT WHERE IDPAY >= 0;
INSERT INTO PAYMENT(QUANTITY,PRICE,TOTALPRICE,PAYTIME,METHODS,IDCART) VALUE(2,200000,200000,'2021-11-19 8:03:01','CASH','17220511182021187');
INSERT INTO PAYMENT(QUANTITY,PRICE,TOTALPRICE,PAYTIME,METHODS,IDCART) VALUE(2,180000,180000,'2021-11-19 9:03:01','CASH','17220511182021187');
INSERT INTO PAYMENT(QUANTITY,PRICE,TOTALPRICE,PAYTIME,METHODS,IDCART) VALUE(1,180000,180000,'2021-11-19 13:03:01','CASH','34270511182021900');